name: issues_triggered
on: [issues, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: output event
        run: echo "${{ toJSON(github.event) }}"
      - name: pwd
        run: pwd
      - name: file
        run: touch file01.log
      - name: ls
        run: ls -al
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: output event
        run: echo "${{ toJSON(github.event) }}"
    
